# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: disabled

# output directory, generated dynamically on each run
output_subdir: null

run:
  dir: ${paths.log_dir}/${data.name}/${experiment.name}/predict/${data.pathway_id}/${data.input_species}__${data.output_species}

job:
  chdir: true
