_target_: pytorch_lightning.Trainer
default_root_dir: ${paths.output_dir}
min_epochs: 10 # prevents early stopping
max_epochs: 50
accelerator: cpu
devices: 1
deterministic: false
enable_model_summary: false
num_sanity_val_steps: 0
